name: 'my_dbt_elt_project'
version: '1.0.0'

profile: 'my_dbt_elt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_dbt_elt_project:

    # example models (optional)
    example:
      +materialized: view

    # your schemas
    staging:
      +schema: STAGING

    marts:
      +schema: MART

    raw:
      +schema: RAW